# BSwear -- Antiswearing!
# By TheBSwearTeam

# start message
showEnabledMessage: true

# Enable join Message
showJoinMessage: true


# cancel message,
#   true = cancel the message
#   false = replace the swear word (best to use this)
cancelMessage: false

# max warnings
maxWarnings: 5


# The Command to be ran when somewon swears
# if you put the command kick it will not work!
command: 'enter command here with out an slash'
commandenable: false


# Kick swearer,
# Kicks the swearer (use this instead of the command /kick)
kickSwearer: false


# Ban swearer,
# Bans the swearer (use this instead of the command /ban)
banSwearer: false


# send title,
#   true = Use the build in TitlesAPI
#   false = Does not use the TitlesAPI
sendTitle: true


# Messages,
messages:
    addword: 'Word Added'
    delword: 'Word Removed'
    noperm: 'No Permission'
    swearmsg: 'No Swearing, Please'
    prefix: '&6[BSwear]&2'


# Block advertising,
advertising:
  - '.com' 
  - ':25565'
  - '.net'
  - 'myserver'
  - 'play.'

# List of players that can see swear messages
# names in lowercase.
allowViewPlayers:
  - 'isaiahmctec'
