# BSwear -- Antiswearing!
# By TheBSwearTeam

# start message
showEnabledMessage: true

# Enable join Message
showJoinMessage: true

# Enables Anti-Spam Checks
antiSpam:
  enable: true
  # Set the spam amount in seconds for cooldown
  spamTimer: 4
  # Set this to how many times a person can speak per spamTimer amount.
  messageAmount: 3
  # Disable if someone can say the same message twice in a row.
  disableSameMessages: true

# cancel message,
#   true = cancel the message
#   false = replace the swear word (best to use this)
cancelMessage: false

# max warnings
maxWarnings: 5


# The Command to be ran when someone swears
# if you put the command kick it will not work!
command: 'enter command here without an slash'
commandenable: false


# Kick swearer,
# Kicks the swearer (use this instead of the command /kick)
kickSwearer: false


# Ban swearer,
# Bans the swearer (use this instead of the command /ban)
banSwearer: false


# send title,
#   true = Use the built in TitlesAPI
#   false = Does not use the TitlesAPI
sendTitle: true


# Messages,
messages:
    addword: 'Word Added'
    delword: 'Word Removed'
    noperm: 'No Permission'
    swearmsg: 'No Swearing, Please'
    prefix: '&6[BSwear]&2'


# Block advertising,
advertising:
  - '.com' 
  - ':25565'
  - '.net'
  - 'myserver'
  - 'play.'

# List of players that can see swear messages
# names in lowercase.
allowViewPlayers:
  - 'isaiahmctec'
