name: BSwear
version: 5.0
authors: [BSwearTeam]
main: io.github.bswearteam.bswear.BSwear
description: Block those nasty players from swearing, 400 preblocked words! Customisable!
permissions:
   bswear.*:
     description: Gives access to all BSwear commands
     children:
       bswear.bypass: true
       bswear.view: true
commands:
    mute:
        description: mute players
    bswear:
        description: bswear command
    swear:
        description: enable swearing for player.
